### ISSUE TITLE
Switch to srt

### ISSUE THREAD

**Issue by vevv** [vevv/subby#14]
[srt](https://github.com/cdown/srt) appears to be a superior library to currently used [pysrt](https://github.com/byroot/pysrt). This would also solve the problem described in #12.

**Comment by xiaoxiaoliya** [comment]
> [srt](https://github.com/cdown/srt) appears to be a superior library to currently used [pysrt](https://github.com/byroot/pysrt). This would also solve the problem described in #12.

Hi, first of all, thank you for creating such an advanced tool.If you have free time, would you consider changing pysrt to srt?
